### ISSUE TITLE
Some Slides

### ISSUE THREAD

**Issue by hkulekci** [TomasVotruba/awesome-doctrine#6]
- [ ] [Effective Doctrine2: Performance Tips for Symfony2 Developers
](https://www.slideshare.net/marcinchwedziak/effective-doctrine2-performance-tips-for-symfony2-developers-33907944)
 - [ ] [Rich domain model with symfony 2.5 and doctrine 2.5](https://www.slideshare.net/_leopro_/rich-domain-model-with-symfony-25-and-doctrine-25)

**Comment by TomasVotruba** [comment]
I think these are already included

**Comment by hkulekci** [comment]
I missed them. right.
